mapfish.Searcher.Map=OpenLayers.Class(mapfish.Searcher,OpenLayers.Control,{protocol:null,mode:null,searchTolerance:3,searchToleranceUnits:'pixels',pixelTolerance:2,delay:300,boxDivClassName:"olHandlerBoxZoomBox",displayDefaultPopup:false,onMouseMove:function(evt){},position:null,popupLonLat:null,response:null,initialize:function(options){this.mode=mapfish.Searcher.Map.CLICK;mapfish.Searcher.prototype.initialize.call(this,options);OpenLayers.Control.prototype.initialize.call(this,options);if(!this.protocol){OpenLayers.Console.error("no protocol set");return;}
switch(this.mode){case mapfish.Searcher.Map.CLICK:this.handler=new OpenLayers.Handler.Click(this,{click:this.handlePoint},{delay:this.delay,pixelTolerance:this.pixelTolerance});break;case mapfish.Searcher.Map.HOVER:this.handler=new OpenLayers.Handler.Hover(this,{pause:this.handlePoint,move:this.cancelSearch},{delay:this.delay,pixelTolerance:this.pixelTolerance});break;case mapfish.Searcher.Map.BOX:this.handler=new OpenLayers.Handler.Box(this,{done:this.handleBox},{boxDivClassName:this.boxDivClassName});break;case mapfish.Searcher.Map.EXTENT:break;default:OpenLayers.Console.error("unsupported mode");return;}},activate:function(){var activated=OpenLayers.Control.prototype.activate.call(this);if(activated){if(this.mode==mapfish.Searcher.Map.EXTENT){this.map.events.register("moveend",this,this.handleMoveend);}else if(this.displayDefaultPopup&&this.protocol.CLASS_NAME=="mapfish.Protocol.TriggerEventDecorator"){this.protocol.events.on({crudfinished:this.displayPopup,scope:this});}}
return activated;},deactivate:function(){var deactivated=OpenLayers.Control.prototype.deactivate.call(this);if(deactivated){if(this.mode==mapfish.Searcher.Map.EXTENT){this.map.events.unregister("moveend",this,this.handleMoveend);}else if(this.displayDefaultPopup&&this.protocol.CLASS_NAME=="mapfish.Protocol.TriggerEventDecorator"){this.protocol.events.un({crudfinished:this.displayPopup,scope:this});}}
return deactivated;},handlePoint:function(evt){this.position=evt.xy;this.popupLonLat=this.map.getLonLatFromViewPortPx(this.position);this.triggerSearch();},handleBox:function(position){if(position instanceof OpenLayers.Bounds){var minXY=this.map.getLonLatFromPixel(new OpenLayers.Pixel(position.left,position.bottom));var maxXY=this.map.getLonLatFromPixel(new OpenLayers.Pixel(position.right,position.top));this.position=new OpenLayers.Bounds(minXY.lon,minXY.lat,maxXY.lon,maxXY.lat);this.popupLonLat=this.position.getCenterLonLat();}else{this.position=position;this.popupLonLat=this.map.getLonLatFromViewPortPx(this.position);}
this.triggerSearch();},handleMoveend:function(){this.position=this.map.getExtent();this.triggerSearch();},triggerSearch:function(){this.cancelSearch();var filter=this.getFilter();filter=this.isFilter(filter)?{filter:filter}:{params:filter};var options=OpenLayers.Util.extend({searcher:this},filter);this.response=this.protocol.read(options);},cancelSearch:function(evt){if(this.response){var response=this.response;if(response.priv&&typeof response.priv.abort=="function"){response.priv.abort();this.response=null;}}
if(this.mode==mapfish.Searcher.Map.HOVER){this.onMouseMove();}},displayPopup:function(response){var features=response.features;if(features&&features.length>0){var k;var html="<table><tr>";for(k in features[0].attributes){html+="<th>"+k+"</th>";}
html+="</tr>";for(var i=0;i<features.length;i++){var attributes=features[i].attributes;html+="<tr>";for(k in attributes){html+="<td>"+attributes[k]+"</td>";}
html+="</tr>";}
html+="</table>";var popup=new OpenLayers.Popup.FramedCloud("mapfish_popup",this.popupLonLat,null,html,null,true);this.map.addPopup(popup,true);}},isFilter:function(obj){return!!obj.CLASS_NAME&&!!obj.CLASS_NAME.match(/^OpenLayers\.Filter/);},getFilter:function(){var filter=null;if(this.mode==mapfish.Searcher.Map.EXTENT&&!this.position){this.position=this.map.getExtent();}
if(this.position){if(this.position instanceof OpenLayers.Bounds){filter=new OpenLayers.Filter.Spatial({type:OpenLayers.Filter.Spatial.BBOX,value:this.position});}else{var tolerance=this.searchTolerance;if(tolerance&&this.searchToleranceUnits=="pixels"){tolerance*=this.map.getResolution();}
var lonlat=this.map.getLonLatFromViewPortPx(this.position);filter={lon:lonlat.lon,lat:lonlat.lat};if(tolerance){filter.tolerance=tolerance;}}
this.position=null;}
return filter;},CLASS_NAME:"mapfish.Searcher.Map"});mapfish.Searcher.Map.CLICK="CLICK";mapfish.Searcher.Map.HOVER="HOVER";mapfish.Searcher.Map.BOX="BOX";mapfish.Searcher.Map.EXTENT="EXTENT";